version: '3.7'
services:
    server:
        container_name: thethreequackinn-server
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:4000
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./wait-for-it.sh:/wait_for_it.sh

    postgres:
        image: postgres:13
        container_name: thethreequackinn-postgres
        restart: always
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./wait-for-it.sh:/wait_for_it.sh

volumes:
    postgres:
        name: thethreequackinn-db
