name: axe
on:
    pull_request:
        branches: [main]
jobs:
    axe:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12.x
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install dependencies
              run: yarn
            - run: yarn build:client
            - run: yarn start:client & npx wait-on http://localhost:3000
            - name: Run axe
              run: |
                  yarn global add @axe-core/cli
                  axe http://localhost:3000 --exit
