name: Deploy Frontend

on:
    push:
        branches: [main]
        paths:
            - 'packages/client/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12.x
            - name: Get yarn cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install dependencies
              run: yarn
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
            - name: Build frontend
              run: yarn build:client
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-west-2
            - name: Sync to S3
              run: aws s3 sync ./packages/client/landing/out s3://thethreequckinn-site
            - name: Remove .html extensions
              run: find ./packages/client/landing/out -type f -name '*.html' | while read HTMLFILE; do
                  BASENAME=${HTMLFILE##*/};
                  FILENAME=${BASENAME%.*};
                  if [[ "$FILENAME" != "index" ]];
                  then
                  aws s3 cp s3://thethreequckinn-site/${BASENAME} s3://thethreequckinn-site/${FILENAME};
                  fi
                  done
